name: macOS Debug Flow

on:
  push:
    branches:
      - T-fix/mac-build

jobs:
  debug:
    runs-on: macos-15-intel

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Forge Make
        run: npm run make